---
- name: Restart PHP-FPM service
  ansible.builtin.service:
    name: php8.3-fpm
    state: restarted

- name: Restart nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
