name: IAGORA Deployment CI

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                path: plugin
                fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install gitlint
              run: python -m pip install --user gitlint requests

            - name: Lint commit messages
              working-directory: plugin
              run: ~/.local/bin/gitlint --commits origin/main..HEAD
